package javaLearning;

public class ExceptionsPartTwo {

	public static void main(String[] args) {
		//we use throws keyword to handle exceptions generated by method
		System.out.println(div(2,0));
	}
	
	static int div(int a,int b) throws ArithmeticException,IndexOutOfBoundsException {//we can use,
		if(b==0) {													//multiple exception as comma separated,
			throw new ArithmeticException("Division by zero");		//list
		}
		else {
			return a/b;
		}
	}
}
//way how to catch multiple exceptions
/*
try {
	//some code
}catch(ExceptionType1 e1) {
	
}catch(ExceptionType2 e2) {
	
}catch(ExceptionType3 e3) {
	
}
*/